version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - azure-70-535-architecting-solutions-caa915d7-edde-41a4-8e44-4b5007092e40.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
